services:
    open_tracing.tracer:
        class: Adtechpotok\Bundle\SymfonyOpenTracing\Service\OpenTracingService
        arguments:
            - '%open_tracing.tracer.service_name%'
            - '%open_tracing.tracer.config%'

    open_tracing.name_getter:
        class: Adtechpotok\Bundle\SymfonyOpenTracing\Service\RootSpanNameBuilder
        arguments:
            - 'http-tracing'
            - 'cli-tracing'

    open_tracing.http_listener:
        class: Adtechpotok\Bundle\SymfonyOpenTracing\EventListener\HttpListener
        arguments:
          - '@open_tracing.tracer'
          - '@open_tracing.name_getter'
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_listener, event: kernel.terminate }
            - { name: kernel.event_listener, event: kernel.exception }
            - { name: kernel.event_listener, event: kernel.response }

    open_tracing.cli_listener:
        class: Adtechpotok\Bundle\SymfonyOpenTracing\EventListener\CliListener
        arguments:
            - '@open_tracing.tracer'
            - '@open_tracing.name_getter'
        tags:
            - {name: kernel.event_listener, event: console.command}
            - {name: kernel.event_listener, event: console.terminate}
            - {name: kernel.event_listener, event: console.error}

    open_tracing.tracer.jaeger:
        class: OpenTracing\Tracer
        factory: ['@open_tracing.tracer', getTracer]
